name: auto-pr

on:
  push:
    branches:
      - "feat/**"
      - "fix/**"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    uses: guilhermelinosp/templates/.github/workflows/auto-pr.yml@df9f66533749a4a3a4b59c18a828a179800de096
    with:
      app-client-id: ${{ vars.HELLNET_ACTIONS_CLIENT_ID }}
    secrets: inherit