name: pipeline

on:
  push:
    branches: [main]
    paths-ignore:
      - '.github/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    name: release
    uses: guilhermelinosp/templates/.github/workflows/release.yml@8f299961846cf1d0cbf7129a99ea6c3095ec3abd
    with:
      app-client-id: ${{ vars.HELLNET_ACTIONS_CLIENT_ID }}
    secrets: inherit
    permissions:
      contents: write
