name: pr-check

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  merge-check:
    uses: guilhermelinosp/templates/.github/workflows/merge-check.yml@9fe39322263723d320cdce780f00d5926059798a # main

  gitleaks:
    uses: guilhermelinosp/templates/.github/workflows/gitleaks.yml@9fe39322263723d320cdce780f00d5926059798a # main

  labeler:
    uses: guilhermelinosp/templates/.github/workflows/labeler.yml@9fe39322263723d320cdce780f00d5926059798a # main
